const SUPABASE_URL="https://lagkkzzqjuwfevoceiaw.supabase.co/rest/v1/";
const SUPABASE_KEY="sb_publishable_XLH_4Q9-E7JDxmrDwrQSgQ_kBktuLwM";
const configured=!SUPABASE_URL.startsWith("YOUR_")&&!SUPABASE_KEY.startsWith("YOUR_");
const sb=configured?supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
const app=document.getElementById("app");let user=null,profile=null,pregnancy=null,family=null,view="home",date=new Date(),filter="all";
const poop={korokoro:["コロコロ","🟤","koro"],banana:["バナナ","🍌","banana"],bechabecha:["ベチャベチャ","💩","becha"],liquid:["液体","💧","liquid"]};
const icons={poop:"💩",medicine:"💊",vomit:"🤢",weight:"⚖️",period:"🌸",note:"📝"};
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const dk=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const fmt=s=>{const d=new Date(s+"T00:00:00");return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`};
const tm=s=>new Date(s).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"});
function flash(t){const x=document.createElement("div");x.textContent=t;x.style="position:fixed;z-index:100;left:50%;top:18px;transform:translateX(-50%);background:#392d42;color:#fff;padding:12px 16px;border-radius:18px;font-weight:900;box-shadow:0 8px 25px #0003";document.body.append(x);setTimeout(()=>x.remove(),2200)}
function modal(title,html){const o=document.createElement("div");o.className="overlay";o.innerHTML=`<div class="modal"><button class="close" onclick="this.closest('.overlay').remove()">×</button><h2>${title}</h2>${html}</div>`;o.onclick=e=>{if(e.target===o)o.remove()};document.body.append(o)}
async function boot(){if(!configured)return config();const {data:{session}}=await sb.auth.getSession();user=session?.user;if(!user)return auth();await loadProfile();if(!profile)return onboarding();await loadFamily();render()}
async function loadProfile(){const {data}=await sb.from("profiles").select("*").eq("id",user.id).maybeSingle();profile=data}
async function loadFamily(){if(!profile?.family_id)return;const {data:f}=await sb.from("families").select("*").eq("id",profile.family_id).single();family=f;const {data:p}=await sb.from("pregnancies").select("*").eq("family_id",profile.family_id).eq("is_active",true).maybeSingle();pregnancy=p}
function config(){app.innerHTML=`<div class="auth"><div class="auth-card"><h1>🌈 💩＆💊</h1><div class="notice">Supabase設定が必要です</div><p class="hint">app.js冒頭のSUPABASE_URLとSUPABASE_KEYを自分のProject URL / Publishable(Anon) Keyに変更してください。</p></div></div>`}
function auth(){app.innerHTML=`<div class="auth"><div class="auth-card"><h1>💩＆💊</h1><p style="text-align:center;font-weight:900">タカちゃん × オタヤダ</p><div class="form-grid"><input id="email" class="input" type="email" placeholder="メールアドレス"><input id="pass" class="input" type="password" placeholder="パスワード"><button class="btn primary" onclick="login()">ログイン</button><button class="btn soft" onclick="signup()">新規登録</button></div></div></div>`}
async function login(){const {error}=await sb.auth.signInWithPassword({email:email.value.trim(),password:pass.value});if(error)return flash(error.message);await boot()}
async function signup(){const {data,error}=await sb.auth.signUp({email:email.value.trim(),password:pass.value});if(error)return flash(error.message);user=data.user;if(user)onboarding()}
function onboarding(){app.innerHTML=`<div class="auth"><div class="auth-card"><h1>🌈 はじめよう</h1><div class="form-grid"><input id="name" class="input" placeholder="表示名（タカちゃん / オタヤダ）"><select id="role" class="input"><option value="wife">👩 妻</option><option value="husband">👨 夫</option></select><input id="due" class="input" type="date" value="2027-01-07"><button class="btn primary" onclick="createFamily()">家族を作って開始</button><p class="hint">2人目の招待は次工程で招待リンクを追加します。</p></div></div></div>`}
async function createFamily(){const n=name.value.trim(),r=role.value,d=due.value;if(!n||!d)return flash("名前と予定日を入力してください");const {data:f,error:e}=await sb.from("families").insert({family_name:"タカちゃん＆オタヤダ"}).select().single();if(e)return flash(e.message);const {error:p}=await sb.from("profiles").insert({id:user.id,family_id:f.id,display_name:n,role:r});if(p)return flash(p.message);const st=new Date(d+"T00:00:00");st.setDate(st.getDate()-280);const {error:pe}=await sb.from("pregnancies").insert({family_id:f.id,mother_profile_id:r==="wife"?user.id:null,due_date:d,pregnancy_start_date:dk(st)});if(pe)return flash(pe.message);await loadProfile();await loadFamily();render()}
async function hr(type,comment=""){const {data,error}=await sb.from("health_records").insert({family_id:profile.family_id,profile_id:user.id,record_type:type,recorded_at:new Date().toISOString(),comment}).select().single();if(error)throw error;return data}
async function poopAdd(k,b){const s=b.querySelector(".splash");s.classList.remove("active");void s.offsetWidth;s.classList.add("active");const c=prompt("ウンチへのコメント（任意）")??"";try{const h=await hr("poop",c);const {error}=await sb.from("poop_records").insert({health_record_id:h.id,poop_type:k,comment:c});if(error)throw error;flash("💩 ブワッ！記録したよ");render()}catch(e){flash(e.message)}}
async function meds(){const {data}=await sb.from("medications").select("*").eq("family_id",profile.family_id).eq("is_active",true).order("created_at");return data||[]}
async function medAdd(id,n,i){try{const h=await hr("medicine");const {error}=await sb.from("medication_logs").insert({health_record_id:h.id,medication_id:id});if(error)throw error;flash(`${i} ${n}を記録！`);render()}catch(e){flash(e.message)}}
function addMed(){modal("💊 薬・サプリを追加",`<div class="form-grid"><input id="mn" class="input" placeholder="例：鉄剤"><input id="mi" class="input" value="💊"><input id="md" class="input" placeholder="メモ"><button class="btn primary" onclick="saveMed()">追加</button></div>`)}
async function saveMed(){const n=mn.value.trim();if(!n)return;const {error}=await sb.from("medications").insert({family_id:profile.family_id,name:n,icon:mi.value||"💊",description:md.value});document.querySelector(".overlay")?.remove();if(error)flash(error.message);else{flash("薬を追加しました");render()}}
function addVomit(){modal("🤢 吐いた記録",`<div class="form-grid"><select id="vs" class="input"><option value="1">軽い</option><option value="3" selected>普通</option><option value="5">とてもつらい</option></select><textarea id="vc" class="input textarea" placeholder="状況・コメント"></textarea><button class="btn pink" onclick="saveVomit()">記録する</button></div>`)}
async function saveVomit(){const c=vc.value;try{const h=await hr("vomit",c);const {error}=await sb.from("vomit_records").insert({health_record_id:h.id,severity:+vs.value,comment:c});if(error)throw error;document.querySelector(".overlay")?.remove();flash("🤢 記録したよ");render()}catch(e){flash(e.message)}}
function addWeight(){modal("⚖️ 体重",`<div class="form-grid"><input id="ww" class="input" type="number" step="0.1" placeholder="kg"><input id="wc" class="input" placeholder="メモ"><button class="btn primary" onclick="saveWeight()">記録</button></div>`)}
async function saveWeight(){const w=parseFloat(ww.value);if(!w)return flash("体重を入力してください");try{const h=await hr("weight",wc.value);const {error}=await sb.from("weight_records").insert({health_record_id:h.id,weight_kg:w,comment:wc.value});if(error)throw error;document.querySelector(".overlay")?.remove();flash("⚖️ 保存したよ");render()}catch(e){flash(e.message)}}
async function dayRecords(d){const {data,error}=await sb.from("health_records").select("id,record_type,recorded_at,comment,poop_records(poop_type,comment),medication_logs(medications(name,icon)),vomit_records(severity,comment),weight_records(weight_kg,comment)").eq("family_id",profile.family_id).gte("recorded_at",d+"T00:00:00").lte("recorded_at",d+"T23:59:59").order("recorded_at",{ascending:false});if(error){console.error(error);return[]}return data||[]}
function entry(r){let n=r.record_type,i=icons[r.record_type];if(r.record_type==="poop"){const m={korokoro:["コロコロ","🟤"],banana:["バナナ","🍌"],bechabecha:["ベチャベチャ","💩"],liquid:["液体","💧"]};[n,i]=m[r.poop_records?.[0]?.poop_type]||["ウンチ","💩"]}if(r.record_type==="medicine"){const m=r.medication_logs?.[0]?.medications;n=m?.name||"薬";i=m?.icon||"💊"}if(r.record_type==="vomit")n="吐いた";if(r.record_type==="weight")n=`体重 ${r.weight_records?.[0]?.weight_kg||""}kg`;return `<div class="entry"><div class="ico">${i}</div><div class="meta"><b>${esc(n)}</b><small>${tm(r.recorded_at)}${r.comment?"　💬 "+esc(r.comment):""}</small></div></div>`}
async function home(){const rs=await dayRecords(dk(date));const ms=await meds();const po=rs.filter(x=>x.record_type==="poop").length,me=rs.filter(x=>x.record_type==="medicine").length,vo=rs.filter(x=>x.record_type==="vomit").length,we=rs.find(x=>x.record_type==="weight")?.weight_records?.[0]?.weight_kg||"-";let g="妊娠情報なし";if(pregnancy){const st=new Date(pregnancy.pregnancy_start_date+"T00:00:00"),days=Math.max(0,Math.floor((Date.now()-st)/86400000));g=`${Math.floor(days/7)}週${days%7}日`}return `<header class="hero"><div class="toilet">🚽</div><h1>💩＆くすり記録</h1><p>タカちゃん × オタヤダ</p><div class="notice" style="display:inline-block;margin-top:8px">🤰 ${g}</div></header><main class="panel"><div class="card datebar"><button onclick="shift(-1)">‹</button><div class="date">${fmt(dk(date))}</div><button onclick="shift(1)">›</button><button class="btn soft" onclick="go('calendar')">📅</button></div><div class="stats"><div class="stat"><b>💩 ${po}</b><small>ウンチ</small></div><div class="stat"><b>💊 ${me}</b><small>薬</small></div><div class="stat"><b>🤢 ${vo}</b><small>吐いた</small></div><div class="stat"><b>⚖️ ${we}</b><small>体重</small></div></div><div class="card"><div class="section-title">💩 ウンチ出た〜！</div><div class="poop-grid">${Object.entries(poop).map(([k,[n,e,c]])=>`<button class="poop ${c}" onclick="poopAdd('${k}',this)"><span class="emoji">${e}</span><span class="name">${n}</span><div class="splash"><i></i><i></i><i></i><i></i><i></i><i></i></div></button>`).join("")}</div></div><div class="card"><div class="section-title">💊 飲んだもの</div><div class="med-grid">${ms.map(m=>`<button class="med ${m.name.includes("葉酸")?"folic":"nausea"}" onclick="medAdd('${m.id}','${esc(m.name)}','${esc(m.icon)}')"><span class="emoji">${esc(m.icon)}</span>${esc(m.name)}</button>`).join("")}<button class="addmed" onclick="addMed()">＋ 薬・サプリを追加</button></div></div><div class="quick-grid"><button class="btn pink" onclick="addVomit()">🤢 吐いた</button><button class="btn primary" onclick="addWeight()">⚖️ 体重</button></div><div class="card"><div class="section-title">📒 今日の記録</div><div class="list">${rs.length?rs.map(entry).join(""):"<div class='empty'>まだ記録はないよ〜！</div>"}</div></div></main>${nav("home")}`}
function shift(n){date.setDate(date.getDate()+n);render()}
async function calendar(){const y=date.getFullYear(),m=date.getMonth(),start=new Date(y,m,1),begin=new Date(start);begin.setDate(1-start.getDay());const end=new Date(y,m+1,0);const {data}=await sb.from("health_records").select("recorded_at,record_type").eq("family_id",profile.family_id).gte("recorded_at",dk(begin)+"T00:00:00").lte("recorded_at",dk(end)+"T23:59:59");const by={};(data||[]).forEach(r=>(by[r.recorded_at.slice(0,10)]??=[]).push(r.record_type));const cells=[];for(let i=0;i<42;i++){const d=new Date(begin);d.setDate(begin.getDate()+i);const k=dk(d),ts=(by[k]||[]).filter(x=>filter==="all"||x===filter);cells.push(`<button class="day ${d.getMonth()!==m?"other":""} ${k===dk(new Date())?"today":""}" onclick="date=new Date('${k}T00:00:00');go('home')"><b>${d.getDate()}</b><div>${ts.map(t=>`<span class="dot">${icons[t]}</span>`).join("")}</div></button>`)}return `<header class="hero"><div class="toilet">📅</div><h1>カレンダー</h1><p>過去の記録をひと目で</p></header><main class="panel"><div class="card datebar"><button onclick="date=new Date(y,m-1,1);render()">‹</button><div class="date">${y}年${m+1}月</div><button onclick="date=new Date(y,m+1,1);render()">›</button></div><div class="tabs">${["all","poop","medicine","vomit","weight"].map(x=>`<button class="tab ${filter===x?"on":""}" onclick="filter='${x}';render()">${x==='all'?"すべて":icons[x]}</button>`).join("")}</div><div class="card"><div class="calendar">${["日","月","火","水","木","金","土"].map(x=>`<div class="cal-head">${x}</div>`).join("")}${cells.join("")}</div></div><div class="card"><button class="btn primary" onclick="eventModal()">📌 予定を追加</button></div></main>${nav("calendar")}`}
function eventModal(){modal("📌 予定",`<div class="form-grid"><input id="et" class="input" placeholder="例：妊婦健診"><input id="ed" class="input" type="date" value="${dk(date)}"><input id="eh" class="input" type="time" value="10:00"><textarea id="ec" class="input textarea" placeholder="メモ"></textarea><button class="btn primary" onclick="saveEvent()">追加</button></div>`)}
async function saveEvent(){if(!et.value.trim())return;const {error}=await sb.from("calendar_events").insert({family_id:profile.family_id,created_by:user.id,title:et.value.trim(),description:ec.value,start_at:`${ed.value}T${eh.value}:00+09:00`,event_type:"other"});document.querySelector(".overlay")?.remove();if(error)flash(error.message);else{flash("予定を追加しました");render()}}
function pregnancyPage(){let g="未設定",left="-";if(pregnancy){const st=new Date(pregnancy.pregnancy_start_date+"T00:00:00"),du=new Date(pregnancy.due_date+"T00:00:00"),days=Math.max(0,Math.floor((Date.now()-st)/86400000));g=`${Math.floor(days/7)}週${days%7}日`;left=Math.ceil((du-Date.now())/86400000)}return `<header class="hero"><div class="toilet">🤰</div><h1>妊娠</h1><p>タカちゃんのダッシュボード</p></header><main class="panel"><div class="card"><div class="notice">🤰 ${g}　／　予定日まで ${left}日</div></div><div class="card"><div class="section-title">📌 今週やること</div><ul><li>次回の健診予定を確認</li><li>先生に聞きたいことを追加</li><li>体重・体調を無理のない範囲で記録</li><li>薬・サプリの記録を確認</li></ul><p class="hint">週数別の一般情報は後から追加できます。医療上の判断は医療機関へ確認してください。</p></div><div class="card"><button class="btn primary" onclick="eventModal()">🏥 健診・予定を追加</button></div></main>${nav("pregnancy")}`}
function settings(){return `<header class="hero"><div class="toilet">❤️</div><h1>夫婦</h1><p>${esc(profile.display_name)}としてログイン中</p></header><main class="panel"><div class="card"><div class="section-title">👩‍❤️‍👨 ${esc(family?.family_name||"家族")}</div><p>現在のアカウント：${esc(profile.display_name)}</p><p class="hint">家族招待リンクは次工程で追加します。</p></div><div class="card"><div class="section-title">🔔 通知</div><p class="hint">Web Pushは公開時にService Worker＋Push購読＋Edge Functionを接続します。</p></div><div class="card"><button class="btn danger" onclick="sb.auth.signOut().then(()=>location.reload())">ログアウト</button></div></main>${nav("settings")}`}
function nav(a){return `<nav class="nav"><button class="${a==='home'?'active':''}" onclick="go('home')"><span>🏠</span>ホーム</button><button class="${a==='calendar'?'active':''}" onclick="go('calendar')"><span>📅</span>カレンダー</button><button class="${a==='pregnancy'?'active':''}" onclick="go('pregnancy')"><span>🤰</span>妊娠</button><button class="${a==='settings'?'active':''}" onclick="go('settings')"><span>❤️</span>夫婦</button><button onclick="allRecords()"><span>📒</span>履歴</button></nav>`}
async function allRecords(){const {data}=await sb.from("health_records").select("record_type,recorded_at,comment").eq("family_id",profile.family_id).order("recorded_at",{ascending:false}).limit(100);modal("📒 最近の記録",`<div class="list">${(data||[]).map(r=>`<div class="entry"><div class="ico">${icons[r.record_type]||"📝"}</div><div class="meta"><b>${r.record_type}</b><small>${new Date(r.recorded_at).toLocaleString("ja-JP")}${r.comment?"　💬 "+esc(r.comment):""}</small></div></div>`).join("")||'<div class="empty">記録なし</div>'}</div>`)}
async function go(v){view=v;render()}async function render(){if(!user)return auth();if(!profile)return onboarding();app.innerHTML=view==='calendar'?await calendar():view==='pregnancy'?pregnancyPage():view==='settings'?settings():await home()}
boot();
